### ISSUE TITLE
Paragraph on "We build a community of practice"

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/open-operations-manifesto#3]

**Comment by itrich** [comment]
# Notes from WG Open Operations Manifesto on 2022-10-07

## Current Draft
From time to time, we're mentally blocked and may need a sparring partner to think outside of the box. We encourage organizations to build internal and external communities of practice to jointly solve these challenges.  Regardeless of the individual level of expertise, everyone contributes. Communities of practice need to establish a low entry barrier to foster a...

Further open topics:
* everyone contributes with their knowledge and/or individual views (both as small tandem or at large scale)
* build a network and connect -> use IRC, Matrix, Discord, whatsoever
    
~Idea: Rephrase headings to "We build a community of practice and share knowledge"~

## Brainstorming
Most important: encourage organizations to allow employees to engage in networks

* Be clear about how this is different from "We share knowledge"
-> Scope is rather real collaboratively work on environments/issues than just theoretical knowledge
* Discussion about internal community of practice vs. cross-organizational communities
* allow every level of expertise, from beginner to expert engineers and let community learn from each other (even experts from rookies)
* build a safe space that allows blame/shame-free collaboration

**Comment by frosty-geek** [comment]
brainstorming had been added in #16
