### ISSUE TITLE
Rework section on authors, supporting organizations, individual signees

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/open-operations-manifesto#37]
We discussed on 2022-11-25 that we should rework the section on authorship, supporting organizations, individual signees

- Highlight well-contributing companies (e.g. by using a full-width logo or golden background)
- Highlight early adaptors and _forethinkes_
   - Divide into _Founding organizations_ and _Supporting organizations_
   - Add authors below the respective founding organizations
- Hide _individual signees_

**Comment by goern** [comment]
I'd like to reopen this issue, as there is no way for individual citizen contributors to bring in their knowledge and forethinkery (is that a word??)

**Comment by itrich** [comment]
Hi @goern,

thank you for your interest. I'm happy to reopen this issue and start the discussion how to additionally add individual signees to the manifesto.
