### ISSUE TITLE
Paragraph on "We’re transparent about our incidents"

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/open-operations-manifesto#5]

**Comment by itrich** [comment]
What about the title: "We publish our incidents and learnings"?

**Comment by itrich** [comment]
We should clarify that publishing incidents only is in the scope of public services. Incident reports that only occured on a specific customer setup should be sent out to the customer, though.

**Comment by itrich** [comment]
# Notes from our meeting on 2022-09-30

* Start with reference to "We believe that failures.." and highlight that transparency should always be blameless!
* Status page with link to a unique identifier that covers the current/past incident
* Incidents don't expire. Be transparent about the history. Let other learn from your past failures.
* Report about the incidents openly: what happened, how did we solve the incident and what are plans to improve our services?
* The incident report should target both: technical as well as non-technical customers with a TL;DR section and a detailed/technical description that covers all the nerdy details.
* Use well-established guidelines (e.g. Google SRE, Atlassian Blameless Postmortem, etc.)
* Reductions (e.g. internal notes vs. public statement) are okay to avoid blaming people directly.
* Finish the chapter with a hint that our proposal is based on parts of the SRE movement (and give kudos)
* Stress that we encourage signing organizations to act acording to the SRE guideline

## Links: 
* https://www.atlassian.com/incident-management/postmortem/blameless
* https://sre.google/sre-book/example-postmortem/
* https://www.blameless.com/sre/improve-postmortem-with-sre-steve-mcghee
---
Thank your for joining and contributing! :tada:

**Comment by FriederikeZelke** [comment]
Draft:
We’re transparent about our incidents

To prevent others from making the same mistakes, we are transparent about all kind of incidents. Talking about failure or incidents must therefore always be open and blameless. To gain full transparency we recommend implementing the following points: Report about the incidents openly with reporting what happened, how you solved the incident and how you want to improve, make it comprehensible with setting a link to a unique identifier that covers the incident at the status page of the project; be also transparent about the history of this incident, but do not name people directly, use, if needed, reductions instead. But keep in mind that publishing incidents is only in the scope of public services. Incident reports that only occurred on a specific customer setup should be sent out to the customer and can be published with the customer´s agreement. When publishing incidents we encourage using well-established guidelines (e.g. Google SRE, Atlassian Blameless Postmortem, etc.), best sign organizations to act according to the SRE guideline. This manifest and all our work is based on the SRE movement – kudos!

**Comment by heinritzkat** [comment]
> We firmly believe that failures make us experts. The way we handle mistakes is how we become better. We think, that handling mistakes in an optimal way means to communicate about them openly and without shame. We are convinced that the culture we build around failures is fundamental for an innovative environment: Not being afraid of making mistakes opens the door to trying new things, without having the fear to fail. We encourage people to raise their voice - not only in case of success, but also in case of failure. We are sure, that this is one of the best ways to prevent others from making the same mistakes we did. In order to achieve the state of full transparency, the history of failures and incidents should be recorded and preserved. Our goal is, that others can therefore truly experience trust, rather than just being told they could.

Lasst mich gern wissen was ihr denkt und ob ihr meint die incidents kommen jetzt zu kurz. Das wäre ein Entwurf für die Zusammenlegung der beiden Paragraphen "failures make us experts" und "Wehre transparent about our incidents"

**Comment by maxwolfs** [comment]
Cool, it flows better than before. I will open a PR with your proposal referencing the already existing PR to get ahead. For further improvements feel free to add further commits to the PR.
