### ISSUE TITLE
Publish version 1.0 of Open Operations Manifesto

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/open-operations-manifesto#8]
We should aim to finish a prerelease in cw 41/42 (Mid October).
A public launch (v1.0) should be released in cw 48 with a reasonable amount of signing companies and signees.

This epic consists of several sub-issues:
- [x] #1 
- [x] #2 
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #7

**Comment by itrich** [comment]
Let's meet again on 2022-08-31 at 12:05 CEST. Eduard will create a public calendar item.

**Comment by garloff** [comment]
https://input.osb-alliance.de/p/2022-scs-sig-open-operations
